### ISSUE TITLE
opt_utils.equals tests whether properties that are functions are equal, angular.equals doesn't

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [bvaughn/jasmine-promise-matchers#15]
Hi, thanks for the really useful library. 

Some of my tests started failing after upgrading to jasmine-promise-matcher 1.1.3 due to the fact that [angular.equals] (https://docs.angularjs.org/api/ng/function/angular.equals) ignores properties that are functions, and I've explicitly relied on this, where opt_utils.equals doesn't. Was there any reason for changing to opt_utils.equals? It seems appropriate to me to use angular.equals because we are testing angular promises.

**Comment by bvaughn** [comment]
Hi @marthinus-engelbrecht,

Sorry for the slow response. Work keeps me busy during the week.

First- you're welcome! Thank you for the kind words. :)

I'm sorry to hear about the failures you're getting in 1.1.3. Looking at the code you're referencing, it looks like it was changed in order to address #10. (Essentially, supporting Jasmine 2 helpers like `jasmine.any`.)

Hm... I'm not immediately sure how to satisfy both cases. Maybe there's a way I can detect Jasmine's asymmetric equality matchers and using `opt_utils.equals` for them while using `angular.equals` for everything else.

**Comment by bvaughn** [comment]
Give [release 2.0.0](https://github.com/bvaughn/jasmine-promise-matchers/releases/tag/2.0.0) a try. Hopefully it fixes the problem you reported! :)

**Comment by marthinus-engelbrecht** [comment]
Cool, thanks for the feedback. Yeah works keeping me busy as well. I'll give it a try when I get a chance and let you know.
