### ISSUE TITLE
Add support for $httpBackend promises

### ISSUE THREAD

**Issue by carlin-q-scott** [bvaughn/jasmine-promise-matchers#24]
When using this with the httpBackend mock I have to call $httpBackend.flush() before I can expect the promise to be resolved. It would be nice if the backend was flushed by this framework. I know that this is tricky because the flush method throws an exception if there are no pending requests.

**Comment by bvaughn** [comment]
Hey @carlin-q-scott,

If you'd be interested in submitting a PR for this feature I'd be happy to review it. Sounds a little questionable though to couple the (generic) Promise assertion helpers with a specific service like httpBackend.

**Comment by carlin-q-scott** [comment]
Well it's a really common service used extensively in testing AngularJS services but I get your point. The proper solution should ensure that it's only flushed when appropriate. I'll look into implementing this when I have some free time.

**Comment by bvaughn** [comment]
A problem with that approach is that an error could indicate that a test failed _but not necessarily_. For instance, if this framework always flushed the `$httpBackend`, sometimes it might error because the `$httpBackend` wasn't even used in a test (in which case the error should be ignored). Other times it might error b'c there were no pending requests (in which case the error should also be ignored). Other times it might error because there are pending requests, in which case the error indicates a problem- either with the test or the code being tested- in which case we would not want to ignore the error. But how could `jasmine-promise-matchers` know which is which?

**Comment by carlin-q-scott** [comment]
I don't remember flush erroring on unmatched requests, I thought that was what verifyNoOutstandingRequest() was for. My plan was to check the request queue and only flush if there's something in it which would cover all the cases you mentioned. If there's somehow no access to the queue then matching on the error message would work.

**Comment by bvaughn** [comment]
Happy to review a PR if you'd like to contribute one.

**Comment by carlin-q-scott** [comment]
Thanks for implementing my recommendation @bvaughn . I'm sorry it generated grumblings from other users too. Hopefully we can make something everyone is happy with.

**Comment by bvaughn** [comment]
It happens. That's kind of to be expected with OSS :)

**Comment by carlin-q-scott** [comment]
Unfortunately that's been my experience too. People do such unexpected things with free and open source software.
