### ISSUE TITLE
v1.0.0 breaks unit tests

### ISSUE THREAD

**Issue by Hyzual** [bvaughn/jasmine-promise-matchers#9]
Hi !

Thanks for these very helpful matchers ! They make testing promises so much easier.
I've found a pretty critical bug: ever since upgrading to 1.0.0, all my tests are broken with the following error:

```
 Error: Injector already created, can not register a module!
```

They break whenever I want to use the `angular.mock.module()` function.

It took me a while to figure out where it came from and I'm pretty sure it's caused by 809f7b6, especially this block starting line 4 in `dist/jasmine-promise-matchers.js`

```javascript
beforeEach(inject(function($injector) {
    $rootScope = $injector.get('$rootScope');
}));
```

I'm not sure what was the intent behind using the `$rootScope`, but as it is I cannot use v1.0.0 and will therefore revert to 0.0.5. Also in case it's needed, I'm using angular 1.3.15 and jasmine 2.3.4.

**Comment by bvaughn** [comment]
Hey @Hyzual. Thanks for the detailed bug report. I'll try to get this fixed this evening when I get home from work!

`$rootScope` was used because I have no way to get at a lower-level `$scope` in order to force promise resolution. But I think I should be able to provide an alternate initialization method that allows users to pass in a `$scope` to use.

**Comment by bvaughn** [comment]
Hi again. Snag version 1.1.1. It will have your fix. :)

**Comment by Hyzual** [comment]
Thanks for the fix, it works ! :)

**Comment by bvaughn** [comment]
Great! Glad to hear :)
